# Spyglass access tutorial

This tutorial demonstrates how to access data from the Pagan Lab using Spyglass.

The example NWB file contains behavioral data from BControl system.

1. Connect to the Spyglass database using DataJoint
2. Query task metadata (event types, state types, action types, and task arguments)
3. Retrieve behavioral data (events, states, actions, and trials)

For visualizations please refer to the [NWB example notebook](https://github.com/catalystneuro/pagan-lab-to-nwb/blob/88292e286f005624ea815b61f893f935b0940f7f/src/pagan_lab_to_nwb/tutorials/arc_behavior_example_notebook.ipynb).

In [15]:
from pathlib import Path
import pandas as pd

DJ_LOCAL_CONF_PATH = Path(
    "/Users/weian/catalystneuro/pagan-lab-to-nwb/src/pagan_lab_to_nwb/spyglass_mock/dj_local_conf.json"
)

import datajoint as dj
dj.config.load(str(DJ_LOCAL_CONF_PATH))
dj.conn(use_tls=False)

from spyglass.settings import raw_dir

nwb_file_name = "sub-H7015_ses-250516a-spyglass.nwb"
nwbfile_path = Path(raw_dir) / nwb_file_name

[2026-01-15 16:30:06,102][INFO]: DataJoint is configured from /Users/weian/catalystneuro/pagan-lab-to-nwb/src/pagan_lab_to_nwb/spyglass_mock/dj_local_conf.json

In [16]:
from spyglass.utils.nwb_helper_fn import get_nwb_file, get_nwb_copy_filename

nwbfile = get_nwb_file(str(nwbfile_path))
nwb_copy_file_name = get_nwb_copy_filename(nwbfile_path.name)
nwb_dict = dict(nwb_file_name=nwb_copy_file_name)

print("NWB file:     ", nwbfile_path)
print("Spyglass copy:", nwb_copy_file_name)

NWB file:      /Volumes/T9/data/Pagan/raw/sub-H7015_ses-250516a-spyglass.nwb
Spyglass copy: sub-H7015_ses-250516a-spyglass_.nwb

## Accessing the task metadata


The task-related general metadata is in `TaskRecordingTypes`.

The `StateTypes` table stores the type of states that occur during the task (e.g. while the animal is waiting for reward), one type per row.

This table is stored in `TaskRecordingTypes.StateTypes()`.

In [38]:
from spyglass.common.common_task_rec import TaskRecordingTypes

print("=== TaskRecordingTypes.StateTypes ===")
state_types = (TaskRecordingTypes.StateTypes() & nwb_dict).fetch(as_dict=True)
state_types_df = pd.DataFrame(state_types).set_index("id")
state_types_df

=== TaskRecordingTypes.StateTypes ===

                          nwb_file_name              state_name
id
0   sub-H7015_ses-250516a-spyglass_.nwb                 state_0
1   sub-H7015_ses-250516a-spyglass_.nwb        sending_trialnum
2   sub-H7015_ses-250516a-spyglass_.nwb  check_next_trial_ready
3   sub-H7015_ses-250516a-spyglass_.nwb          wait_for_cpoke
4   sub-H7015_ses-250516a-spyglass_.nwb    wait_for_cpoke_wait2
5   sub-H7015_ses-250516a-spyglass_.nwb      wait_for_cpoke_dir
6   sub-H7015_ses-250516a-spyglass_.nwb     wait_for_cpoke_freq
7   sub-H7015_ses-250516a-spyglass_.nwb      wait_for_cpoke_bis
8   sub-H7015_ses-250516a-spyglass_.nwb             nic_prestim
9   sub-H7015_ses-250516a-spyglass_.nwb                   cpoke
10  sub-H7015_ses-250516a-spyglass_.nwb                cpoke_in
11  sub-H7015_ses-250516a-spyglass_.nwb               cpoke_out
12  sub-H7015_ses-250516a-spyglass_.nwb           wait_for_cout
13  sub-H7015_ses-250516a-spyglass_.nwb          wait_for_spoke
14  sub-H7015_ses-250516a-spyglass_.nwb               hit_state
15  sub-H7015_ses-250516a-spyglass_.nwb              hit_state2
16  sub-H7015_ses-250516a-spyglass_.nwb             error_state
17  sub-H7015_ses-250516a-spyglass_.nwb              wait_state
18  sub-H7015_ses-250516a-spyglass_.nwb         nic_error_state
19  sub-H7015_ses-250516a-spyglass_.nwb        nic_error_state2
20  sub-H7015_ses-250516a-spyglass_.nwb           timeout_state
21  sub-H7015_ses-250516a-spyglass_.nwb          clean_up_state

The `EventTypes` is a column-based table to store the type of events that occur during the task (e.g. port poke from the animal), one type per row.

This table is stored in `TaskRecordingTypes.EventTypes()`.

In [23]:
event_types = (TaskRecordingTypes.EventTypes() & nwb_dict).fetch(as_dict=True)
event_types_df = pd.DataFrame(event_types).set_index("id")
print("=== TaskRecordingTypes.EventTypes ===")
event_types_df

=== TaskRecordingTypes.EventTypes ===

                          nwb_file_name event_name
id
0   sub-H7015_ses-250516a-spyglass_.nwb          C
1   sub-H7015_ses-250516a-spyglass_.nwb          L
2   sub-H7015_ses-250516a-spyglass_.nwb          R

The `ActionTypes` is a column-based table to store the type of actions that occur during the task (e.g. sound output from the acquisition system), one type per row.

This table is stored in `TaskRecordingTypes.ActionTypes()`.

In [24]:
action_types = (TaskRecordingTypes.ActionTypes() & nwb_dict).fetch(as_dict=True)
action_types_df = pd.DataFrame(action_types).set_index("id")
print("=== TaskRecordingTypes.ActionTypes ===")
action_types_df

=== TaskRecordingTypes.ActionTypes ===

                          nwb_file_name     action_name
id
0   sub-H7015_ses-250516a-spyglass_.nwb   direct_reward
1   sub-H7015_ses-250516a-spyglass_.nwb  stimulatorwave
2   sub-H7015_ses-250516a-spyglass_.nwb     cpoke_timer

The arguments of the task is stored in an `Arguments` table which can be accessed as `TaskRecordingTypes.Arguments()`.

In [37]:
arguments = (TaskRecordingTypes.Arguments() & nwb_dict).fetch(as_dict=True)
arguments_df = pd.DataFrame(arguments)
print("\n=== TaskRecordingTypes.Arguments ===")
arguments_df[["nwb_file_name", "argument_name", "argument_description", "expression"]]

=== TaskRecordingTypes.Arguments ===

,nwb_file_name,argument_name,argument_description,expression
0,sub-H7015_ses-250516a-spyglass_.nwb,CommentsSection_CommentsShow,Show/Hide Comments panel,0
1,sub-H7015_ses-250516a-spyglass_.nwb,HistorySection_correct_coherent,%hit coh,0.7129909365558912
2,sub-H7015_ses-250516a-spyglass_.nwb,HistorySection_correct_incoherent,%hit incoh,nan
3,sub-H7015_ses-250516a-spyglass_.nwb,HistorySection_dir_correct,%hit dir,0.7129909365558912
4,sub-H7015_ses-250516a-spyglass_.nwb,HistorySection_freq_correct,%hit freq,nan
5,sub-H7015_ses-250516a-spyglass_.nwb,HistorySection_last_result,no description,correct
6,sub-H7015_ses-250516a-spyglass_.nwb,HistorySection_left_correct,%hit left,0.7331460674157303
7,sub-H7015_ses-250516a-spyglass_.nwb,HistorySection_nTrials,no description,909
8,sub-H7015_ses-250516a-spyglass_.nwb,HistorySection_nValid,no description,662
9,sub-H7015_ses-250516a-spyglass_.nwb,HistorySection_percent_violations,%viol,0.2717271727172717
10,sub-H7015_ses-250516a-spyglass_.nwb,HistorySection_previous_stage,no description,Stage 2
11,sub-H7015_ses-250516a-spyglass_.nwb,HistorySection_previous_task,no description,Direction
12,sub-H7015_ses-250516a-spyglass_.nwb,HistorySection_result,no description,1
13,sub-H7015_ses-250516a-spyglass_.nwb,HistorySection_right_correct,%hit right,0.6895424836601307
14,sub-H7015_ses-250516a-spyglass_.nwb,HistorySection_title,no description,HistorySection
15,sub-H7015_ses-250516a-spyglass_.nwb,HistorySection_total_correct,%hit,0.7129909365558912
16,sub-H7015_ses-250516a-spyglass_.nwb,HistorySection_was_block_switch,no description,0
17,sub-H7015_ses-250516a-spyglass_.nwb,HistorySection_was_err,no description,0
18,sub-H7015_ses-250516a-spyglass_.nwb,HistorySection_was_hit,no description,1
19,sub-H7015_ses-250516a-spyglass_.nwb,HistorySection_was_nic_err,no description,0
20,sub-H7015_ses-250516a-spyglass_.nwb,HistorySection_was_timeout,no description,0
21,sub-H7015_ses-250516a-spyglass_.nwb,HistorySection_was_wait,no description,0
22,sub-H7015_ses-250516a-spyglass_.nwb,OptoSection_cere1,no description,0
23,sub-H7015_ses-250516a-spyglass_.nwb,OptoSection_cere2,R power,0
24,sub-H7015_ses-250516a-spyglass_.nwb,OptoSection_cere3,R power,0
25,sub-H7015_ses-250516a-spyglass_.nwb,OptoSection_cere4,R power,0
26,sub-H7015_ses-250516a-spyglass_.nwb,OptoSection_cere5,R power,0
27,sub-H7015_ses-250516a-spyglass_.nwb,OptoSection_delay_start,delay start,0
28,sub-H7015_ses-250516a-spyglass_.nwb,OptoSection_delay_stop,delay stop,0
29,sub-H7015_ses-250516a-spyglass_.nwb,OptoSection_lab1,no description,cere1
30,sub-H7015_ses-250516a-spyglass_.nwb,OptoSection_lab2,no description,cere2
31,sub-H7015_ses-250516a-spyglass_.nwb,OptoSection_lab3,no description,cere3
32,sub-H7015_ses-250516a-spyglass_.nwb,OptoSection_lab4,no description,cere4
33,sub-H7015_ses-250516a-spyglass_.nwb,OptoSection_lab5,no description,cere5
34,sub-H7015_ses-250516a-spyglass_.nwb,OptoSection_lab6,no description,This Opto Pulse
35,sub-H7015_ses-250516a-spyglass_.nwb,OptoSection_lab7,no description,Opto History
36,sub-H7015_ses-250516a-spyglass_.nwb,OptoSection_left_correct_opto_0,L,0
37,sub-H7015_ses-250516a-spyglass_.nwb,OptoSection_left_correct_opto_bi,L,0
38,sub-H7015_ses-250516a-spyglass_.nwb,OptoSection_left_correct_opto_left,L,0
39,sub-H7015_ses-250516a-spyglass_.nwb,OptoSection_left_correct_opto_right,L,0
40,sub-H7015_ses-250516a-spyglass_.nwb,OptoSection_max_left_opto_power,L power,800
41,sub-H7015_ses-250516a-spyglass_.nwb,OptoSection_max_right_opto_power,R power,800
42,sub-H7015_ses-250516a-spyglass_.nwb,OptoSection_nTrials_opto_0,T,0
43,sub-H7015_ses-250516a-spyglass_.nwb,OptoSection_nTrials_opto_bi,T,0
44,sub-H7015_ses-250516a-spyglass_.nwb,OptoSection_nTrials_opto_left,T,0
45,sub-H7015_ses-250516a-spyglass_.nwb,OptoSection_nTrials_opto_right,T,0
46,sub-H7015_ses-250516a-spyglass_.nwb,OptoSection_opto_active,"If on, sends opto pulses to cerebro",0
47,sub-H7015_ses-250516a-spyglass_.nwb,OptoSection_opto_connected,"If 1, we are connected to cerebro",0
48,sub-H7015_ses-250516a-spyglass_.nwb,OptoSection_opto_left_power,L power,0
49,sub-H7015_ses-250516a-spyglass_.nwb,OptoSection_opto_right_power,R power,0
50,sub-H7015_ses-250516a-spyglass_.nwb,OptoSection_opto_setup,Show/Hide Opto setup panel,0
51,sub-H7015_ses-250516a-spyglass_.nwb,OptoSection_opto_start_ref,opto start ref,off
52,sub-H7015_ses-250516a-spyglass_.nwb,OptoSection_opto_stop_ref,opto stop ref,off
53,sub-H7015_ses-250516a-spyglass_.nwb,OptoSection_opto_type,the current type of opto,Full Trial
54,sub-H7015_ses-250516a-spyglass_.nwb,OptoSection_pa1,no description,L
55,sub-H7015_ses-250516a-spyglass_.nwb,OptoSection_pa2,no description,R
56,sub-H7015_ses-250516a-spyglass_.nwb,OptoSection_pa3,no description,B
57,sub-H7015_ses-250516a-spyglass_.nwb,OptoSection_pa4,no description,0
58,sub-H7015_ses-250516a-spyglass_.nwb,OptoSection_percent_violations_opto_0,V,0
59,sub-H7015_ses-250516a-spyglass_.nwb,OptoSection_percent_violations_opto_bi,V,0
60,sub-H7015_ses-250516a-spyglass_.nwb,OptoSection_percent_violations_opto_left,V,0
61,sub-H7015_ses-250516a-spyglass_.nwb,OptoSection_percent_violations_opto_right,V,0
62,sub-H7015_ses-250516a-spyglass_.nwb,OptoSection_right_correct_opto_0,R,0
63,sub-H7015_ses-250516a-spyglass_.nwb,OptoSection_right_correct_opto_bi,R,0
64,sub-H7015_ses-250516a-spyglass_.nwb,OptoSection_right_correct_opto_left,R,0
65,sub-H7015_ses-250516a-spyglass_.nwb,OptoSection_right_correct_opto_right,R,0
66,sub-H7015_ses-250516a-spyglass_.nwb,ProtocolsSection_n_completed_trials,The number of completed trials.,909
67,sub-H7015_ses-250516a-spyglass_.nwb,ProtocolsSection_n_done_trials,The number of done trials.,909
68,sub-H7015_ses-250516a-spyglass_.nwb,ProtocolsSection_n_started_trials,The number of started trials.,910
69,sub-H7015_ses-250516a-spyglass_.nwb,SavingSection_autosave_frequency,no description,20
70,sub-H7015_ses-250516a-spyglass_.nwb,SavingSection_data_file,no description,C:\ratter\SoloData\Data\Nuria\H7015\data_@TaskSwitch6_Nuria_H7015_250516_ASV\data_@TaskSwitch6_Nuria_H7015_250516_0878_0897.mat
71,sub-H7015_ses-250516a-spyglass_.nwb,SavingSection_experimenter,no description,Nuria
72,sub-H7015_ses-250516a-spyglass_.nwb,SavingSection_hostname,no description,localhost
73,sub-H7015_ses-250516a-spyglass_.nwb,SavingSection_interactive_by_default,"When this is ""interactive"",\n",1
74,sub-H7015_ses-250516a-spyglass_.nwb,SavingSection_n_autosave_calls,no description,911
75,sub-H7015_ses-250516a-spyglass_.nwb,SavingSection_ratname,no description,H7015
76,sub-H7015_ses-250516a-spyglass_.nwb,SavingSection_SaveTime,no description,16-May-2025 17:54:49
77,sub-H7015_ses-250516a-spyglass_.nwb,SavingSection_save_all_data_to_sql,no description,0
78,sub-H7015_ses-250516a-spyglass_.nwb,SavingSection_settings_file,no description,C:\ratter\SoloData\Settings\Nuria\H7015\settings_@TaskSwitch6_Nuria_H7015_250515a.mat
79,sub-H7015_ses-250516a-spyglass_.nwb,SavingSection_settings_file_load_time,no description,739753.6130927663
80,sub-H7015_ses-250516a-spyglass_.nwb,SavingSection_title,no description,SavingSection
81,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_ErrorSoundBal,no description,0
82,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_ErrorSoundCntrst,no description,500
83,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_ErrorSoundCollisions,no description,1
84,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_ErrorSoundCRatio,no description,5
85,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_ErrorSoundDur1,no description,0.5
86,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_ErrorSoundDur2,no description,0.5
87,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_ErrorSoundFMAmp,no description,200
88,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_ErrorSoundFMFreq,no description,5
89,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_ErrorSoundForceCount,no description,0
90,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_ErrorSoundFreq1,no description,333
91,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_ErrorSoundFreq2,no description,333
92,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_ErrorSoundFreqS,no description,0
93,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_ErrorSoundGap,no description,0
94,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_ErrorSoundHead,no description,ErrorSound
95,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_ErrorSoundLoop,no description,1
96,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_ErrorSoundSigma,no description,100
97,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_ErrorSoundStereo_1st,no description,0
98,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_ErrorSoundStyle,no description,PClick
99,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_ErrorSoundTau,no description,0.1
100,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_ErrorSoundVol,no description,0.0035
101,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_ErrorSoundVol2,no description,0.1
102,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_ErrorSoundWidth,no description,5
103,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_ErrorSoundWNP,no description,0
104,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_HitSoundBal,no description,0
105,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_HitSoundCntrst,no description,500
106,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_HitSoundCollisions,no description,1
107,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_HitSoundCRatio,no description,5
108,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_HitSoundDur1,no description,0.1
109,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_HitSoundDur2,no description,0.3
110,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_HitSoundFMAmp,no description,200
111,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_HitSoundFMFreq,no description,5
112,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_HitSoundForceCount,no description,0
113,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_HitSoundFreq1,no description,1000
114,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_HitSoundFreq2,no description,5000
115,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_HitSoundFreqS,no description,0
116,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_HitSoundGap,no description,0
117,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_HitSoundHead,no description,HitSound
118,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_HitSoundLeft_Click_Times,no description,0
119,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_HitSoundLoop,no description,0
120,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_HitSoundRight_Click_Times,no description,0
121,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_HitSoundSigma,no description,100
122,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_HitSoundStereo_1st,no description,0
123,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_HitSoundStyle,no description,ToneSweep
124,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_HitSoundTau,no description,0.05
125,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_HitSoundVol,no description,0.0025
126,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_HitSoundVol2,no description,0.1
127,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_HitSoundWidth,no description,3
128,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_HitSoundWNP,no description,0
129,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_Task1SoundBal,no description,0
130,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_Task1SoundCntrst,no description,500
131,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_Task1SoundCollisions,no description,1
132,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_Task1SoundCRatio,no description,5
133,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_Task1SoundDur1,no description,1
134,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_Task1SoundDur2,no description,0.5
135,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_Task1SoundFMAmp,no description,600
136,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_Task1SoundFMFreq,no description,5
137,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_Task1SoundForceCount,no description,0
138,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_Task1SoundFreq1,no description,4000
139,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_Task1SoundFreq2,no description,1000
140,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_Task1SoundFreqS,no description,0
141,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_Task1SoundGap,no description,0
142,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_Task1SoundHead,no description,Task1Sound
143,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_Task1SoundLeft_Click_Times,no description,0
144,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_Task1SoundLoop,no description,0
145,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_Task1SoundRight_Click_Times,no description,0
146,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_Task1SoundSigma,no description,100
147,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_Task1SoundStereo_1st,no description,0
148,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_Task1SoundStyle,no description,ToneFMWiggle
149,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_Task1SoundTau,no description,0.1
150,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_Task1SoundVol,no description,0.005
151,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_Task1SoundVol2,no description,0.1
152,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_Task1SoundWidth,no description,3
153,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_Task1SoundWNP,no description,0
154,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_Task2SoundBal,no description,0
155,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_Task2SoundCntrst,no description,500
156,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_Task2SoundCollisions,no description,1
157,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_Task2SoundCRatio,no description,5
158,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_Task2SoundDur1,no description,1
159,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_Task2SoundDur2,no description,0.5
160,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_Task2SoundFMAmp,no description,1800
161,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_Task2SoundFMFreq,no description,15
162,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_Task2SoundForceCount,no description,0
163,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_Task2SoundFreq1,no description,9000
164,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_Task2SoundFreq2,no description,1000
165,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_Task2SoundFreqS,no description,0
166,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_Task2SoundGap,no description,0
167,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_Task2SoundHead,no description,Task2Sound
168,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_Task2SoundLeft_Click_Times,no description,0
169,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_Task2SoundLoop,no description,0
170,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_Task2SoundRight_Click_Times,no description,0
171,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_Task2SoundSigma,no description,100
172,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_Task2SoundStereo_1st,no description,0
173,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_Task2SoundStyle,no description,ToneFMWiggle
174,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_Task2SoundTau,no description,0.1
175,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_Task2SoundVol,no description,0.005
176,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_Task2SoundVol2,no description,0.1
177,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_Task2SoundWidth,no description,3
178,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_Task2SoundWNP,no description,0
179,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_TimeoutSoundBal,no description,0
180,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_TimeoutSoundCntrst,no description,500
181,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_TimeoutSoundCollisions,no description,1
182,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_TimeoutSoundCRatio,no description,5
183,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_TimeoutSoundDur1,no description,1
184,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_TimeoutSoundDur2,no description,0.5
185,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_TimeoutSoundFMAmp,no description,200
186,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_TimeoutSoundFMFreq,no description,5
187,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_TimeoutSoundForceCount,no description,0
188,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_TimeoutSoundFreq1,no description,1000
189,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_TimeoutSoundFreq2,no description,1000
190,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_TimeoutSoundFreqS,no description,0
191,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_TimeoutSoundGap,no description,0
192,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_TimeoutSoundHead,no description,TimeoutSound
193,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_TimeoutSoundLeft_Click_Times,no description,0
194,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_TimeoutSoundLoop,no description,1
195,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_TimeoutSoundRight_Click_Times,no description,0
196,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_TimeoutSoundSigma,no description,100
197,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_TimeoutSoundStereo_1st,no description,0
198,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_TimeoutSoundStyle,no description,SpectrumNoise
199,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_TimeoutSoundTau,no description,0.1
200,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_TimeoutSoundVol,no description,0.0025
201,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_TimeoutSoundVol2,no description,0.1
202,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_TimeoutSoundWidth,no description,3
203,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_TimeoutSoundWNP,no description,0
204,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_ViolationSoundBal,no description,0
205,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_ViolationSoundCntrst,no description,111
206,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_ViolationSoundCollisions,no description,1
207,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_ViolationSoundCRatio,no description,1
208,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_ViolationSoundDur1,no description,1
209,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_ViolationSoundDur2,no description,0.5
210,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_ViolationSoundFMAmp,no description,200
211,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_ViolationSoundFMFreq,no description,5
212,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_ViolationSoundForceCount,no description,0
213,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_ViolationSoundFreq1,no description,8000
214,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_ViolationSoundFreq2,no description,2222
215,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_ViolationSoundFreqS,no description,0
216,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_ViolationSoundGap,no description,0
217,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_ViolationSoundHead,no description,ViolationSound
218,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_ViolationSoundLeft_Click_Times,no description,0
219,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_ViolationSoundLoop,no description,1
220,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_ViolationSoundRight_Click_Times,no description,0
221,sub-H7015_ses-250516a-spyglass_.nwb,SoundInterface_ViolationSoundSigma,no description,14

## Accessing the behavioral data

The `TaskRecording` stores the object references for events, states, and actions that occurred during the task.

In [40]:
from spyglass.common.common_task_rec import TaskRecording

task_recording = (TaskRecording() & nwb_dict).fetch(as_dict=True)

print("\n=== TaskRecording ===")
task_recording_df = pd.DataFrame(task_recording)
task_recording_df

=== TaskRecording ===

,nwb_file_name,actions_object_id,events_object_id,states_object_id,trials_object_id
0,sub-H7015_ses-250516a-spyglass_.nwb,bb38d4c7-58bc-4c5c-ab9d-e88288953d34,4ffe2b8f-18a3-4751-bf8f-e46090163517,1cc869ca-b28f-44e5-871b-31523e8962f4,1cac2baa-2741-4fe4-9176-61bcb56d1e55

### Actions

In [84]:
actions_df = (TaskRecording() & nwb_dict).fetch1_dataframe("actions")
actions_df["action_type"] = actions_df["action_type"].apply(lambda x: x.values[0][0])
actions_df.head()

    timestamp     action_type value  duration
id
0     61.2053  stimulatorwave   out    0.0099
1     62.6052     cpoke_timer   out    0.0001
2     75.8231  stimulatorwave   out    0.0099
3     77.2230     cpoke_timer   out    0.0001
4     77.9078   direct_reward   out    0.0126

### Events

In [83]:
events_df = (TaskRecording() & nwb_dict).fetch1_dataframe("events")
events_df["event_type"] = events_df["event_type"].apply(lambda x: x.values[0][0])
events_df.head()

    timestamp event_type value  duration
id
0     34.6646          R   out    0.0335
1     34.8936          R   out    0.0775
2     35.1562          R   out    0.0801
3     35.3584          R   out    0.1147
4     36.9975          L   out    0.0282

### States

In [80]:
states_df = (TaskRecording() & nwb_dict).fetch1_dataframe("states")
states_df["state_type"] = states_df["state_type"].apply(lambda x: x.values[0][0])
states_df.head()

    start_time  stop_time              state_type
id
0      32.3360    67.1255                 state_0
1      32.3360    32.3361          wait_for_cpoke
2      32.3361    67.1255  check_next_trial_ready
3      33.3361    33.3362    wait_for_cpoke_wait2
4      33.3362    34.3362      wait_for_cpoke_dir

## Trials

In [47]:
trials_df = (TaskRecording() & nwb_dict).fetch1_dataframe("trials")
trials_df.head()

,start_time,stop_time,states,events,actions,HistorySection_hit_history,HistorySection_side_history,HistorySection_task_history,HistorySection_incoh_history,HistorySection_gammadir_history,HistorySection_gammafreq_history,HistorySection_result_history,HistorySection_hit_history_task,HistorySection_incoh_history_task
id,,,,,,,,,,,,,,
0,32.3360,67.1255,start_time stop_time \ id 0 32.3360 67.1255 1 32.3360 32.3361 2 32.3361 67.1255 3 33.3361 33.3362 4 33.3362 34.3362 5 34.3362 61.2042 6 61.2042 61.2052 7 61.2052 61.2055 8 61.2055 62.6052 9 62.6052 62.6887 10 62.6887 63.1248 11 63.1248 67.1248 12 67.1248 67.1255 state_type id 0 state_name id 0 state_0 1 state_name id 3 wait_for_cpoke 2 state_name id 2 check_next_trial_ready 3 state_name id 4 wait_for_cpoke_wait2 4 state_name id 5 wait_for_cpoke_dir 5 state_name id 7 wait_for_cpoke_bis 6 state_name id 8 nic_prestim 7 state_name id 9 cpoke 8 state_name id 10 cpoke_in 9 state_name id 12 wait_for_cout 10 state_name id 13 wait_for_spoke 11 state_name id 16 error_state 12 state_name id 21 clean_up_state,timestamp event_type value duration id 0 34.6646 event_name id 2 R out 0.0335 1 34.8936 event_name id 2 R out 0.0775 2 35.1562 event_name id 2 R out 0.0801 3 35.3584 event_name id 2 R out 0.1147 4 36.9975 event_name id 1 L out 0.0282 5 37.0930 event_name id 1 L out 0.0490 6 37.2777 event_name id 1 L out 0.0499 7 61.2042 event_name id 0 C out 1.4845 8 63.1248 event_name id 2 R out 0.0391 9 63.2803 event_name id 2 R out 0.0467 10 64.2236 event_name id 1 L out 0.0708,timestamp action_type value \ id 0 61.2053 action_name id 1 stimulatorwave out 1 62.6052 action_name id 2 cpoke_timer out duration id 0 0.0099 1 0.0001,0.0,l,d,0,-4,-0.0,2,1.0,0.0
1,67.1256,78.4210,start_time stop_time \ id 13 67.1256 67.1257 14 67.1256 78.4210 15 67.1257 68.1257 16 68.1257 68.1258 17 68.1258 69.1258 18 69.1258 75.8220 19 75.8220 75.8230 20 75.8230 75.8233 21 75.8233 76.4636 22 76.4636 76.4939 23 76.4939 77.2230 24 77.2230 77.3497 25 77.3497 77.9065 26 77.9065 77.9068 27 77.9068 78.4203 28 78.4203 78.4210 29 78.4210 78.4210 state_type id 13 state_name id 2 check_next_trial_ready 14 state_name id 0 state_0 15 state_name id 3 wait_for_cpoke 16 state_name id 4 wait_for_cpoke_wait2 17 state_name id 5 wait_for_cpoke_dir 18 state_name id 7 wait_for_cpoke_bis 19 state_name id 8 nic_prestim 20 state_name id 9 cpoke 21 state_name id 10 cpoke_in 22 state_name id 11 cpoke_out 23 state_name id 10 cpoke_in 24 state_name id 12 wait_for_cout 25 state_name id 13 wait_for_spoke 26 state_name id 14 hit_state 27 state_name id 15 hit_state2 28 state_name id 21 clean_up_state 29 state_name id 2 check_next_trial_ready,timestamp event_type value duration id 11 75.8220 event_name id 0 C out 0.6416 12 76.4939 event_name id 0 C out 0.8558 13 77.9065 event_name id 1 L out 0.0040 14 77.9145 event_name id 1 L out 0.0269,timestamp action_type value \ id 2 75.8231 action_name id 1 stimulatorwave out 3 77.2230 action_name id 2 cpoke_timer out 4 77.9078 action_name id 0 direct_reward out duration id 2 0.0099 3 0.0001 4 0.0126,1.0,l,d,0,-4,-0.0,1,1.0,0.0
2,78.4727,85.5819,start_time stop_time \ id 30 78.4727 78.4728 31 78.4727 85.5819 32 78.4728 79.4728 33 79.4728 79.4729 34 79.4729 80.4729 35 80.4729 82.8863 36 82.8863 82.8873 37 82.8873 82.8876 38 82.8876 84.2873 39 84.2873 84.4633 40 84.4633 85.0673 41 85.0673 85.0676 42 85.0676 85.5812 43 85.5812 85.5819 44 85.5819 85.5819 state_type id 30 state_name id 2 check_next_trial_ready 31 state_name id 0 state_0 32 state_name id 3 wait_for_cpoke 33 state_name id 4 wait_for_cpoke_wait2 34 state_name id 5 wait_for_cpoke_dir 35 state_name id 7 wait_for_cpoke_bis 36 state_name id 8 nic_prestim 37 state_name id 9 cpoke 38 state_name id 10 cpoke_in 39 state_name id 12 wait_for_cout 40 state_name id 13 wait_for_spoke 41 state_name id 14 hit_state 42 state_name id 15 hit_state2 43 state_name id 21 clean_up_state 44 state_name id 2 check_next_trial_ready,timestamp event_type value duration id 15 78.8166 event_name id 1 L out 0.0503 16 78.9499 event_name id 1 L out 0.0553 17 79.0888 event_name id 1 L out 0.0582 18 79.2335 event_name id 1 L out 0.0557 19 79.3837 event_name id 1 L out 0.0474 20 79.5287 event_name id 1 L out 0.0388 21 79.6674 event_name id 1 L out 0.0418 22 79.8137 event_name id 1 L out 0.0554 23 79.9705 event_name id 1 L out 0.0600 24 80.1428 event_name id 1 L out 0.0126 25 80.2851 event_name id 1 L out 0.0293 26 80.4628 event_name id 1 L out 0.0067 27 80.6260 event_name id 1 L out 0.0320 28 80.7903 event_name id 1 L out 0.0325 29 80.8322 event_name id 1 L out 0.0191 30 80.9687 event_name id 1 L out 0.0228 31 81.1462 event_name id 1 L out 0.0051 32 81.3069 event_name id 1 L out 0.0342 33 81.3559 event_name id 1 L out 0.0115 34 81.3697 event_name id 1 L out 0.0022 35 81.4938 event_name id 1 L out 0.0575 36 82.8863 event_name id 0 C out 1.5770 37 85.0673 event_name id 1 L out 0.0188,timestamp action_type value \ id 5 82.8874 action_name id 1 stimulatorwave out 6 84.2873 action_name id 2 cpoke_timer out 7 85.0686 action_name id 0 direct_reward out duration id 5 0.0099 6 0.0001 7 0.0126,1.0,l,d,0,-4,-0.0,1,0.0,0.0
3,85.8839,96.7632,start_time stop_time \ id 45 85.8839 85.8840 46 85.8839 96.7632 47 85.8840 86.8840 48 86.8840 86.8841 49 86.8841 87.8841 50 87.8841 90.4924 51 90.4924 90.4934 52 90.4934 90.4937 53 90.4937 91.8934 54 91.8934 91.9765 55 91.9765 92.7625 56 92.7625 96.7625 57 96.7625 96.7632 58 96.7632 96.7632 state_type id 45 state_name id 2 check_next_trial_ready 46 state_name id 0 state_0 47 state_name id 3 wait_for_cpoke 48 state_name id 4 wait_for_cpoke_wait2 49 state_name id 5 wait_for_cpoke_dir 50 state_name id 7 wait_for_cpoke_bis 51 state_name id 8 nic_prestim 52 state_name id 9 cpoke 53 state_name id 10 cpoke_in 54 state_name id 12 wait_for_cout 55 state_name id 13 wait_for_spoke 56 state_name id 16 error_state 57 state_name id 21 clean_up_state 58 state_name id 2 check_next_trial_ready,timestamp event_type value duration id 38 86.0032 event_name id 1 L out 0.0611 39 86.1611 event_name id 1 L out 0.0550 40 86.3163 event_name id 1 L out 0.0552 41 86.4736 event_name id 1 L out 0.0603 42 86.6357 event_name id 1 L out 0.0666 43 86.8119 event_name id 1 L out 0.0658 44 86.9895 event_name id 1 L out 0.0373 45 87.0379 event_name id 1 L out 0.0076 46 87.0513 event_name id 1 L out 0.0015 47 87.1615 event_name id 1 L out 0.0608 48 87.3391 event_name id 1 L out 0.0247 49 87.5076 event_name id 1 L out 0.0525 50 87.5666 event_name id 1 L out 0.0019 51 89.7043 event_name id 1 L out 0.0322 52 89.8438 event_name id 1 L out 0.0544 53 90.0197 event_name id 1 L out 0.0394 54 90.4924 event_name id 0 C out 1.4841 55 92.7625 event_name id 1 L out 0.0338 56 93.0161 event_name id 1 L out 0.0774 57 93.1858 event_name id 1 L out 0.0698 58 93.3593 event_name id 1 L out 0.0600 59 93.6711 event_name id 1 L out 0.0840 60 93.8628 event_name id 1 L out 0.0825 61 94.0439 event_name id 1 L out 0.0789 62 94.2388 event_name id 1 L out 0.0572 63 94.4196 event_name id 1 L out 0.0530,timestamp action_type value \ id 8 90.4935 action_name id 1 stimulatorwave out 9 91.8934 action_name id 2 cpoke_timer out duration id 8 0.0099 9 0.0001,0.0,r,d,0,4,0.0,2,1.0,0.0
4,96.7633,109.6879,start_time stop_time \ id 59 96.7633 109.6879 60 96.7633 96.7634 61 96.7634 97.7634 62 97.7634 97.7635 63 97.7635 98.7635 64 98.7635 103.6127 65 103.6127 103.6128 66 103.6128 104.6128 67 104.6128 105.4897 68 105.4897 106.4897 69 106.4897 106.6304 70 106.6304 106.6314 71 106.6314 106.6317 72 106.6317 106.7810 73 106.7810 106.8295 74 106.8295 107.0326 75 107.0326 107.0721 76 107.0721 108.0314 77 108.0314 108.5653 78 108.5653 109.1607 79 109.1607 109.1610 80 109.1610 109.6872 81 109.6872 109.6879 82 109.6879 109.6879 state_type id 59 state_name id 0 state_0 60 state_name id 2 check_next_trial_ready 61 state_name id 3 wait_for_cpoke 62 state_name id 4 wait_for_cpoke_wait2 63 state_name id 5 wait_for_cpoke_dir 64 state_name id 7 wait_for_cpoke_bis 65 state_name id 8 nic_prestim 66 state_name id 3 wait_for_cpoke 67 state_name id 4 wait_for_cpoke_wait2 68 state_name id 5 wait_for_cpoke_dir 69 state_name id 7 wait_for_cpoke_bis 70 state_name id 8 nic_prestim 71 state_name id 9 cpoke 72 state_name id 10 cpoke_in 73 state_name id 11 cpoke_out 74 state_name id 10 cpoke_in 75 state_name id 11 cpoke_out 76 state_name id 10 cpoke_in 77 state_name id 12 wait_for_cout 78 state_name id 13 wait_for_spoke 79 state_name id 14 hit_state 80 state_name id 15 hit_state2 81 state_name id 21 clean_up_state 82 state_name id 2 check_next_trial_ready,timestamp event_type value duration id 64 103.1817 event_name id 2 R out 0.0532 65 103.6127 event_name id 0 C out 0.0001 66 103.6129 event_name id 0 C out 0.2635 67 103.9256 event_name id 0 C out 0.0351 68 103.9781 event_name id 0 C out 0.1174 69 104.1355 event_name id 0 C out 1.3542 70 105.9511 event_name id 1 L out 0.0540 71 106.1247 event_name id 1 L out 0.0091 72 106.1513 event_name id 1 L out 0.0277 73 106.6304 event_name id 0 C out 0.1506 74 106.8295 event_name id 0 C out 0.2031 75 107.0721 event_name id 0 C out 1.4932 76 109.1607 event_name id 2 R out 0.0221,timestamp action_type value \ id 10 106.6315 action_name id 1 stimulatorwave out 11 108.0314 action_name id 2 cpoke_timer out 12 109.1620 action_name id 0 direct_reward out duration id 10 0.0099 11 0.0001 12 0.0252,1.0,r,d,0,4,0.0,1,0.0,0.0

In [87]:
# Get the first trial's states
trials_df.states[0]

,start_time,stop_time,state_type
id,,,
0,32.3360,67.1255,state_name id 0 state_0
1,32.3360,32.3361,state_name id 3 wait_for_cpoke
2,32.3361,67.1255,state_name id 2 check_next_trial_ready
3,33.3361,33.3362,state_name id 4 wait_for_cpoke_wait2
4,33.3362,34.3362,state_name id 5 wait_for_cpoke_dir
5,34.3362,61.2042,state_name id 7 wait_for_cpoke_bis
6,61.2042,61.2052,state_name id 8 nic_prestim
7,61.2052,61.2055,state_name id 9 cpoke
8,61.2055,62.6052,state_name id 10 cpoke_in
9,62.6052,62.6887,state_name id 12 wait_for_cout
10,62.6887,63.1248,state_name id 13 wait_for_spoke
11,63.1248,67.1248,state_name id 16 error_state
12,67.1248,67.1255,state_name id 21 clean_up_state